sudo: false
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36-django22-drf38
    - python: 3.6
      env: TOXENV=py36-django22-drf39
    - python: 3.6
      env: TOXENV=py36-django22-drf310
    - python: 3.6
      env: TOXENV=py36-django22-drf311
    - python: 3.6
      env: TOXENV=py36-django30-drf310
    - python: 3.6
      env: TOXENV=py36-django30-drf311
    - python: 3.6
      env: TOXENV=py36-djangomaster-drfmaster

    - python: 3.7
      env: TOXENV=py37-django22-drf38
      dist: xenial
      sudo: required
    - python: 3.7
      env: TOXENV=py37-django22-drf39
      dist: xenial
      sudo: required
    - python: 3.7
      env: TOXENV=py37-django22-drf310
      dist: xenial
      sudo: required
    - python: 3.7
      env: TOXENV=py37-django22-drf311
      dist: xenial
      sudo: required
    - python: 3.7
      env: TOXENV=py37-django30-drf310
      dist: xenial
      sudo: required
    - python: 3.7
      env: TOXENV=py37-django30-drf311
      dist: xenial
      sudo: required
    - python: 3.7
      env: TOXENV=py37-djangomaster-drfmaster
      dist: xenial
      sudo: required

    - python: 3.8
      env: TOXENV=py38-django22-drf38
      dist: xenial
      sudo: required
    - python: 3.8
      env: TOXENV=py38-django22-drf39
      dist: xenial
      sudo: required
    - python: 3.8
      env: TOXENV=py38-django22-drf310
      dist: xenial
      sudo: required
    - python: 3.8
      env: TOXENV=py38-django22-drf311
      dist: xenial
      sudo: required
    - python: 3.8
      env: TOXENV=py38-django30-drf310
      dist: xenial
      sudo: required
    - python: 3.8
      env: TOXENV=py38-django30-drf311
      dist: xenial
      sudo: required
    - python: 3.8
      env: TOXENV=py38-djangomaster-drfmaster
      dist: xenial
      sudo: required

  allow_failures:
    - env: TOXENV=py36-djangomaster-drfmaster
    - env: TOXENV=py37-djangomaster-drfmaster
    - env: TOXENV=py38-djangomaster-drfmaster

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
